#! /usr/bin/env bash

source .env

: ${DHCPHELPER_TAG:=latest}
: ${DHCPHELPER_NETWORK:=srvr}

# dhcphelper:
#   restart: unless-stopped
#   container_name: dhcphelper
#   image: homeall/dhcphelper:${DHCPHELPER_TAG}
#   environment:
#     IP: pihole
#     TZ: 'Europe/London'
#   cap_add:
#     - NET_ADMIN
#   ports:
#     - "67:67/udp"
#   networks:
#     - srvr    

PIHOLE_IP=$(docker-ip pihole)

docker run -d \
  --privileged \
  --name dhcphelper \
  --env "IP=${PIHOLE_IP}" \
  --env "TZ=Australia/Sydney" \
  --cap-add NET_ADMIN \
  --network "${DHCPHELPER_NETWORK}" \
  --publish 67:67/udp \
  homeall/dhcphelper:"${DHCPHELPER_TAG}"
